"""Command-line interface for pjvmpack."""

import argparse
import sys

from .errors import PackError
from .mapfile import emit_map
from .options import PackOptions
from .pack import pack_pjvm


def _parse_pin_hints(text):
    if not text:
        return None
    return [int(x) for x in text.split(",")]


def _write_hex_dump(pjvm):
    print("\nHex dump:")
    for i in range(0, len(pjvm), 16):
        hex_part = " ".join(f"{b:02X}" for b in pjvm[i:i + 16])
        ascii_part = "".join(chr(b) if 32 <= b < 127 else "."
                             for b in pjvm[i:i + 16])
        print(f"  {i:04X}: {hex_part:<48s} {ascii_part}")


def _write_c_header(path, pjvm):
    with open(path, "w") as f:
        f.write("// Auto-generated by pjvmpack.py\n")
        f.write("static const unsigned char pjvm_program[] = {\n")
        for i in range(0, len(pjvm), 16):
            line = ", ".join(f"0x{b:02X}" for b in pjvm[i:i + 16])
            f.write(f"    {line},\n")
        f.write("};\n")
        f.write(f"static const unsigned int pjvm_program_size = {len(pjvm)};\n")
    print(f"Wrote {path}")


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Convert .class files to .pjvm for picoJVM")
    parser.add_argument("classfiles", nargs="+", help="Input .class files")
    parser.add_argument("-o", "--output", help="Output .pjvm file")
    parser.add_argument("-v", "--verbose", action="store_true",
                        help="Show details")
    parser.add_argument("--hex", action="store_true",
                        help="Print hex dump of output")
    parser.add_argument("--c-header", help="Emit C header with embedded array")
    parser.add_argument("--emit-map", action="store_true",
                        help="Emit .pjvmmap sidecar for exception trace decoding")
    parser.add_argument("--v2", action="store_true",
                        help="Deprecated; ignored (use --format)")
    parser.add_argument("--format", choices=("auto", "v3", "v4"), default="auto",
                        help="Output format: auto-select v3/v4, or force one")
    parser.add_argument("--pin-hints",
                        help="Comma-separated method indices to recommend pinning")
    parser.add_argument("--no-cp-compact", action="store_true",
                        help="Emit legacy per-class CP resolution slices")
    parser.add_argument("--pack-method-table", action="store_true",
                        help="Use compact v4 method-table encoding")
    args = parser.parse_args(argv)

    class_data_list = []
    for path in args.classfiles:
        with open(path, "rb") as f:
            class_data_list.append(f.read())

    options = PackOptions(
        verbose=args.verbose,
        v2=args.v2,
        pin_hints=_parse_pin_hints(args.pin_hints),
        compact_cp=not args.no_cp_compact,
        pjvm_format=args.format,
        pack_method_table=args.pack_method_table,
    )
    try:
        pjvm, class_order, method_table = pack_pjvm(
            class_data_list,
            verbose=options.verbose,
            v2=options.v2,
            pin_hints=options.pin_hints,
            compact_cp=options.compact_cp,
            pjvm_format=options.pjvm_format,
            pack_method_table=options.pack_method_table,
        )
    except PackError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    out_path = args.output
    if not out_path:
        base = args.classfiles[0].replace(".class", "")
        out_path = base + ".pjvm"
    with open(out_path, "wb") as f:
        f.write(pjvm)
    print(f"Wrote {out_path} ({len(pjvm)} bytes)")

    if args.hex:
        _write_hex_dump(pjvm)

    if args.c_header:
        _write_c_header(args.c_header, pjvm)

    if args.emit_map:
        map_data = emit_map(class_order, method_table)
        map_path = out_path.replace(".pjvm", ".pjvmmap")
        with open(map_path, "wb") as f:
            f.write(map_data)
        print(f"Wrote {map_path} ({len(map_data)} bytes)")

    return 0


__all__ = ["main"]
